[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [

]
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "zhuxining", email = "zhuxining@outlook.com"},
]
dependencies = [
    "fastapi-users[beanie,oauth]>=11.0.0",
    "fastapi>=0.95.1",
    "uvicorn[standard]>=0.22.0",
    "setuptools>=67.7.2",
    "loguru>=0.7.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
