version: '1.0'
name: pipeline-20230616
displayName: pipeline-20230616
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-9c90c4a1
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - sed '/-e/d' requirements.lock > requirements.lock
          - pip install --user -r requirements.txt
          - python --version
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
